import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Home, Settings, User } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main
        className={`${geistSans.variable} ${geistMono.variable} antialiased pb-16`}
      >
        {children}
        <nav className="flex justify-around p-4 text-center text-sm text-gray-500 bg-neutral-800 fixed bottom-0 w-full">
          <Link href={"/home"} className="text-white" title="Home">
            <Home />
          </Link>
          <Link href={"/"} className="text-white" title="Home">
            <Home />
          </Link>
          <Link href={"/"} className="text-white" title="Home">
            <Home />
          </Link>
          <Link href={"/profile"} className="text-white" title="Home">
            <User />
          </Link>
          <Link href={"/setting"} className="text-white" title="Home">
            <Settings />
          </Link>
        </nav>
      </main>
  );
}
